name: Test Container Action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    
    name: A job to say hello
    steps:
    
      - name: Hello world action step
        id: hello
        uses: judeakinwale/docker-container-action@v2
#         uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'jude'
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
