
name: Testing Container Action in Azure Workflows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Build application artifact
      uses: actions/upload-artifact@v3
      with:
        name: ci-artifact
        path: .
    
    - name: Build container
      uses: docker/build-push-action@v1
      with:
        username: judeakinwale
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: judeakinwale/publish-packages/ci-test
        tag_with_sha: true
        
    # - name: Create and Publish Docker Image
    #   uses: manusa/actions-publish-docker@v1.1.2
    #   with:
    #     name: judeakinwale/testing
    #     tag: ci-test
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

